package com.fujitsu.telehealth.model;

public class HtmlTemplate {

	private String htmlContent;

	public String getHtmlContent() {
		return htmlContent;
	}

	public void setHtmlContent(String token, String fullname) {
		StringBuilder sb = new StringBuilder();
		
			sb.append("<body style=\"background-color: #f4f4f4; margin: 0 !important; padding: 0 !important;\">\r\n"
					+ "    <!-- HIDDEN PREHEADER TEXT -->\r\n"
					+ "    <div style=\"display: none; font-size: 1px; color: #fefefe; line-height: 1px; font-family: 'Lato', Helvetica, Arial, sans-serif; max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden;\"> We're thrilled to have you here! Get ready to dive into your new account. </div>\r\n"
					+ "    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
					+ "        <!-- LOGO -->\r\n"
					+ "        <tr>\r\n"
					+ "            <td bgcolor=\"#fff\" align=\"center\">\r\n"
					+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\r\n"
					+ "                    <tr>\r\n"
					+ "                        <td align=\"center\" valign=\"top\" style=\"padding: 40px 10px 40px 10px;\"> </td>\r\n"
					+ "                    </tr>\r\n"
					+ "                </table>\r\n"
					+ "            </td>\r\n"
					+ "        </tr>\r\n"
					+ "        <tr>\r\n"
					+ "            <td bgcolor=\"#fff\" align=\"center\" style=\"padding: 0px 10px 0px 10px;\">\r\n"
					+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\r\n"
					+ "                    <tr>\r\n"
					+ "                        <td bgcolor=\"#1c87c9\" align=\"center\" valign=\"top\" style=\"padding: 40px 20px 20px 20px; border-radius: 4px 4px 0px 0px; color: #fff; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 48px; font-weight: 400; letter-spacing: 4px; line-height: 48px;\">\r\n"
					+ "                            <h1 style=\"font-size: 48px; font-weight: 400;\">Welcome!</h1> <div>" + fullname + "</div/>\r\n"
					+ "                        </td>\r\n"
					+ "                    </tr>\r\n"
					+ "                </table>\r\n"
					+ "            </td>\r\n"
					+ "        </tr>\r\n"
					+ "        <tr>\r\n"
					+ "            <td bgcolor=\"#f4f4f4\" align=\"center\" style=\"padding: 0px 10px 0px 10px;\">\r\n"
					+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\r\n"
					+ "                    <tr>\r\n"
					+ "                        <td bgcolor=\"#1c87c9\" align=\"left\" style=\"padding: 20px 30px 40px 30px; color: #fff; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
					+ "                            <p style=\"margin: 0;\">We're excited to have you get started. First, you need to confirm your account. Just press the button below.</p>\r\n"
					+ "                        </td>\r\n"
					+ "                    </tr>\r\n"
					+ "                    <tr>\r\n"
					+ "                        <td bgcolor=\"#1c87c9\" align=\"left\">\r\n"
					+ "                            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
					+ "                                <tr>\r\n"
					+ "                                    <td bgcolor=\"#ffffff\" align=\"center\" style=\"padding: 20px 30px 60px 30px;\">\r\n"
					+ "                                        <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
					+ "                                            <tr>\r\n"
					+ "                                                <td align=\"center\" style=\"border-radius: 3px;\" bgcolor=\"#1c87c9\"><a href=\"http://localhost:8080/telehealth/verify?token=" + token + "\"target=\"_blank\" style=\"font-size: 20px; font-family: Helvetica, Arial, sans-serif; color: #ffffff; text-decoration: none; color: #ffffff; text-decoration: none; padding: 15px 25px; border-radius: 2px; border: 1px solid #1c87c9; display: inline-block;\">Confirm Account</a></td>\r\n"
					+ "                                            </tr>\r\n"
					+ "                                        </table>\r\n"
					+ "                                    </td>\r\n"
					+ "                                </tr>\r\n"
					+ "                            </table>\r\n"
					+ "                        </td>\r\n"
					+ "                    </tr>\r\n"
					+ "                    <!-- COPY -->\r\n"
					+ "                    <tr>\r\n"
					+ "                        <td bgcolor=\"#ffffff\" align=\"left\" style=\"padding: 0px 30px 0px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
					+ "                            <p style=\"margin: 0;\">If that doesn't work, copy and paste the following link in your browser:</p>\r\n"
					+ "                        </td>\r\n"
					+ "                    </tr>\r\n"
					+ "                    <!-- COPY -->\r\n"
					+ "                    <tr>\r\n"
					+ "                        <td bgcolor=\"#ffffff\" align=\"left\" style=\"padding: 20px 30px 20px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
					+ "                            <p style=\"margin: 0;\"><a href=\"http://localhost:8080/telehealth/verify?token=" + token + "\"" + "target=\"_blank\" style=\"color: #1c87c9;\">http://localhost:8080/telehealth/verify?token=" + token + "</a></p>\r\n"
					+ "                        </td>\r\n"
					+ "                    </tr>\r\n"
					+ "                    <tr>\r\n"
					+ "                        <td bgcolor=\"#ffffff\" align=\"left\" style=\"padding: 0px 30px 20px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
					+ "                            <p style=\"margin: 0;\">If you have any questions, just reply to this email—we're always happy to help out.</p>\r\n"
					+ "                        </td>\r\n"
					+ "                    </tr>\r\n"
					+ "                    <tr>\r\n"
					+ "                        <td bgcolor=\"#ffffff\" align=\"left\" style=\"padding: 0px 30px 40px 30px; border-radius: 0px 0px 4px 4px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
					+ "                            <p style=\"margin: 0;\">Cheers,<br>Health Care Team</p>\r\n"
					+ "                        </td>\r\n"
					+ "                    </tr>\r\n"
					+ "                </table>\r\n"
					+ "            </td>\r\n"
					+ "        </tr>\r\n"
					+ "        <tr>\r\n"
					+ "            <td bgcolor=\"#f4f4f4\" align=\"center\" style=\"padding: 30px 10px 0px 10px;\">\r\n"
					+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\r\n"
					+ "                    <tr>\r\n"
					+ "                        <td bgcolor=\"#1c87c9\" align=\"center\" style=\"padding: 30px 30px 30px 30px; border-radius: 4px 4px 4px 4px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\">\r\n"
					+ "                            <h2 style=\"font-size: 20px; font-weight: 400; color: #fff; margin: 0;\">Need more help?</h2>\r\n"
					+ "                            <p style=\"margin: 0;\"><a href=\"#\" target=\"_blank\" style=\"color: #fff;\">We&rsquo;re here to help you out</a></p>\r\n"
					+ "                        </td>\r\n"
					+ "                    </tr>\r\n"
					+ "                </table>\r\n"
					+ "            </td>\r\n"
					+ "        </tr>\r\n"
					+ "        <tr>\r\n"
					+ "            <td bgcolor=\"#f4f4f4\" align=\"center\" style=\"padding: 0px 10px 0px 10px;\">\r\n"
					+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\r\n"
					+ "                    <tr>\r\n"
					+ "                        <td bgcolor=\"#f4f4f4\" align=\"left\" style=\"padding: 0px 30px 30px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 18px;\"> <br>\r\n"
					+ "                            <p style=\"margin: 0;\">If these emails get annoying, please feel free to <a href=\"#\" target=\"_blank\" style=\"color: #111111; font-weight: 700;\">unsubscribe</a>.</p>\r\n"
					+ "                        </td>\r\n"
					+ "                    </tr>\r\n"
					+ "                </table>\r\n"
					+ "            </td>\r\n"
					+ "        </tr>\r\n"
					+ "    </table>\r\n"
					+ "</body>\r\n");
		htmlContent = sb.toString();
	}

}

